name: PluginName
version: @version@-@apiversion@
description: An empty plugin for Spigot with Maven
authors: [ DartPower, AnotherContributorName ]
website: https://github.com/dptmc/DPT-PluginRepoTemplate
main: io.dpteam.PluginName.Main